export interface User {
    investorId: number;
    name: string;
    emailConfirmed: boolean;
    level: number;
    levelName: string | null;
    type: number;
    typeName: string | null;
    lastRequestUpgradeStatus: any;
    requestUpgradeId: any;
    lastRequestUpgradeStatusName: any;
    idNumber: number;
    gender: number;
    genderName: string;
    bankName: string | null;
    iban: string | null;
    personalIban: string | null;
    ibanbalance: number;
    totalWritingMoney: number;
    totalStocks: number;
    totalWriting: number;
    bankTitle: string | null;
    image: string | null;
    needUpdate: boolean;
    lastUpdateDate: string;
    extraIncomeId: number | null;
    extraIncomeText: string | null;
    isForeign: boolean;
    ibanFund: string | null;
    personalIbanFund: string | null;
    ibanFundBalance: number;
    needUpdateAssets: boolean;
    needUpdateGeneral: boolean;
    commercialRegistryFile: string | null;
    companyPolicy: string | null;
    establishmentContract: string | null;
    shareholdersDecision: string | null;
    resolutionPartners: string | null;
    boardDecision: string | null;
    ibanSukuk: string | null;
    ibanSukukBalance: number;
    totalWritingMoneyFund: number;
    totalStocksFund: number;
    totalWritingFund: number;
    totalWritingMoneySukuk: number;
    totalStocksSukuk: number;
    totalWritingSukuk: number;
    termesCondition: boolean;
    acknowledgement: boolean;
    agreeAccount: boolean;
    locked: boolean;
    email: string | null;
    idExpiryYear: number;
    idExpiryMonth: number;
    idExpiryDay: number;
    birthYear: number;
    birthMonth: number;
    birthDay: number;
    employmentStatus: string;
    address: string | null;
    commercialRegistrationNo: string | null;
    endDateYear: number;
    endDateMonth: number;
    endDateDay: number;
    startDateYear: number;
    startDateMonth: number;
    startDateDay: number;
    phoneNumber: string | null;
    id: number;
    isComplete: boolean | null;
    completePercent: number;
} 