# name: Deploy Angular to IIS

# on:
#   push:
#     branches:
#       - development

# jobs:
#   build-and-deploy:
#     runs-on: self-hosted  # this is your Windows IIS server

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '18'

#     - name: Install dependencies
#       run: npm ci

#     - name: Build Angular app
#       run: npm run build -- --configuration production

#     - name: Copy build to IIS folder
#       run: |
#         $destination = "C:\inetpub\wwwroot\FrontEnd\sharikek-frontend\browser"
#         if (Test-Path $destination) {
#           Remove-Item "$destination\*" -Recurse -Force
#         } else {
#           New-Item -ItemType Directory -Force -Path $destination
#         }
#         Copy-Item -Path ".\dist\YOUR_PROJECT_NAME\*" -Destination $destination -Recurse
#       shell: pwsh


name: Self-hosted Runner Test

on: [push]

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Hello World
        run: echo "Runner is alive and working"
