name: Build and Deploy Angular to IIS

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js (you can remove this if your runner already has Node + Angular CLI installed globally)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./your-angular-project

      # 4️⃣ Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: ./your-angular-project

      # 5️⃣ Replace or modify files in a specific directory
      - name: Replace files in config directory
        run: |
          echo "Replacing config files..."
          cp ./custom-files/config.json ./your-angular-project/dist/my-app/assets/config/config.json
          rm -f ./your-angular-project/dist/my-app/assets/config/old-file.txt

      # 6️⃣ Deploy to IIS directory
      - name: Deploy to IIS
        run: |
          echo "Deploying to IIS folder..."
          rm -rf "C:/inetpub/wwwroot/my-angular-app/*"
          cp -r ./your-angular-project/dist/my-app/* "C:/inetpub/wwwroot/my-angular-app/"
