name: Test Self-Hosted Runner

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "✅ Hello World from self-hosted runner!"
