name: Runner Test 1

on:
  push:
    branches:
      - development

jobs:
  ping:
    runs-on: self-hosted
    steps:
      - name: Say hello
        run: echo "✅ Runner is alive on $(hostname) at $(date)"
