name: Test Self-Hosted Runner (cmd echo)

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Say Hello via cmd
        shell: cmd
        run: echo Hello from CMD
